/*
* Service Manager
*
* API version: 1.0
* Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package servicemanager

// The broker error
type ErrorBrokerError struct {
	// The broker status code.
	StatusCode int32 `json:"statusCode,omitempty"`
	// A machine-readable error string that may be returned by the broker.
	ErrorMessage string `json:"errorMessage,omitempty"`
	// A human-readable description of the error that may be returned by the broker.
	Description string `json:"description,omitempty"`
	// ResponseError is set to the error that occurred when unmarshalling a response body from the broker.
	ResponseError string `json:"responseError,omitempty"`
}
