version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: "tuesday"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      day: "tuesday"    
# Terraform package ecosystem is supported, but in a too low version
