version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      terraform-framework:
        patterns:
          - "github.com/hashicorp/terraform-plugin-*"
      other-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/hashicorp/terraform-plugin-*"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
