/*
 * Accounts Service
 *
 * The Accounts service provides REST APIs that are responsible for the management of global accounts, and the creation and management of directories, subaccounts, and their custom properties/tags.  Global accounts represent a business entity and contain contract information, including customer details and purchased entitlements. The global account is the context for billing each customer.  Use the subaccount APIs to structure your global account according to your organization's and project's requirements regarding members, authorizations, and quotas. This service also provides you with APIs for creating and managing directories. While the use of directories is optional, they allow you to further organize and manage your subaccounts according to your specific technical and business needs. The service also lets you manage the custom properties/tags that you associate with your directories and subaccounts. NOTE: These APIs are relevant only for cloud management tools feature set B. For details and information about whether this applies to your global account, see [Cloud Management Tools - Feature Set Overview](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/caf4e4e23aef4666ad8f125af393dfb2.html).  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cis

type SubaccountResponseObject struct {
	// Whether the subaccount can use beta services and applications.
	BetaEnabled bool `json:"betaEnabled"`
	// Details of the user that created the subaccount.
	CreatedBy string `json:"createdBy,omitempty"`
	// The date the subaccount was created. Dates and times are in UTC format.
	CreatedDate Time `json:"createdDate"`
	// (Deprecated) Contains information about the labels assigned to a specified subaccount. This field supports only single values per key and is now replaced by the string array \"labels\", which supports multiple values per key. The \"customProperties\" field returns only the first value of any label key that has multiple values assigned to it.
	CustomProperties []PropertyResponseObject `json:"customProperties,omitempty"`
	// A description of the subaccount for customer-facing UIs.
	Description string `json:"description"`
	// A descriptive name of the subaccount for customer-facing UIs.
	DisplayName string `json:"displayName"`
	// The unique ID of the subaccount's global account.
	GlobalAccountGUID string `json:"globalAccountGUID"`
	// Unique ID of the subaccount.
	Guid string `json:"guid"`
	// Contains information about the labels assigned to a specified subaccount. Labels are represented in a JSON array of key-value pairs; each key has up to 10 corresponding values. This field replaces the deprecated \"customProperties\" field, which supports only single values per key.
	Labels map[string][]string `json:"labels,omitempty"`
	// The date the subaccount was last modified. Dates and times are in UTC format.
	ModifiedDate Time `json:"modifiedDate"`
	// The features of parent entity of the subaccount.
	ParentFeatures []string `json:"parentFeatures"`
	// The GUID of the subaccount’s parent entity. If the subaccount is located directly in the global account (not in a directory), then this is the GUID of the global account.
	ParentGUID string `json:"parentGUID"`
	//The type of the parent entity.
	ParentType string `json:"parentType"`
	// The region in which the subaccount was created.
	Region string `json:"region"`
	// The current state of the subaccount.
	State string `json:"state"`
	// Information about the state of the subaccount.
	StateMessage string `json:"stateMessage,omitempty"`
	// The subdomain that becomes part of the path used to access the authorization tenant of the subaccount. Must be unique within the defined region. Use only letters (a-z), digits (0-9), and hyphens (not at the start or end). Maximum length is 63 characters. Cannot be changed after the subaccount has been created.
	Subdomain string `json:"subdomain"`
	// The technical name of the subaccount. Refers to: (1) the platform-based account name for Neo subaccounts, or (2) the account identifier (tenant ID) in XSUAA for multi-environment subaccounts.
	TechnicalName string `json:"technicalName"`
	// Whether the subaccount is used for production purposes. This flag can help your cloud operator to take appropriate action when handling incidents that are related to mission-critical accounts in production systems. Do not apply for subaccounts that are used for non-production purposes, such as development, testing, and demos. Applying this setting this does not modify the subaccount. * <b>UNSET:</b> Global account or subaccount admin has not set the production-relevancy flag. Default value. * <b>NOT_USED_FOR_PRODUCTION:</b> Subaccount is not used for production purposes. * <b>USED_FOR_PRODUCTION:</b> Subaccount is used for production purposes.
	UsedForProduction string `json:"usedForProduction"`
}
