/*
 * Entitlements Service
 *
 * The Entitlements service provides REST APIs that manage the assignments of entitlements and quotas to subaccounts and directories.   Entitlements and their quota are automatically assigned to the global account when a customer order is fulfilled. Use the APIs in this service to manage the distribution of this global quota to your directories and subaccounts.   NOTE: These APIs are relevant only for cloud management tools feature set B. For details and information about whether this applies to your global account, see [Cloud Management Tools - Feature Set Overview](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/caf4e4e23aef4666ad8f125af393dfb2.html).  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cis_entitlements

type AssignedServicePlanSubaccountDto struct {
	// The quantity of the entitlement that is assigned to the root global account or directory.
	Amount float64 `json:"amount,omitempty"`
	// Whether the plan is automatically distributed to the subaccounts that are located in the directory.
	AutoAssign bool `json:"autoAssign,omitempty"`
	// Specifies if the plan was automatically assigned regardless of any action by an admin. This applies to entitlements that are always available to subaccounts and cannot be removed.
	AutoAssigned bool `json:"autoAssigned,omitempty"`
	// The amount of the entitlement to automatically assign to subaccounts that are added in the future to the entitlement's assigned directory.   Requires that autoAssign is set to TRUE, and there is remaining quota for the entitlement. To automatically distribute to subaccounts that are added in the future to the directory, distribute must be set to TRUE.
	AutoDistributeAmount int32 `json:"autoDistributeAmount,omitempty"`
	// Date the subaccount has been created. Dates and times are in UTC format.
	CreatedDate Time `json:"createdDate,omitempty"`
	// The unique ID of the global account or directory to which the entitlement is assigned.
	EntityId string `json:"entityId,omitempty"`
	// The current state of the service plan assignment. * <b>STARTED:</b> CRUD operation on an entity has started. * <b>PROCESSING:</b> A series of operations related to the entity is in progress. * <b>PROCESSING_FAILED:</b> The processing operations failed. * <b>OK:</b> The CRUD operation or series of operations completed successfully.
	EntityState string `json:"entityState,omitempty"`
	// The type of entity to which the entitlement is assigned. * <b>SUBACCOUNT:</b> The entitlement is assigned to a subaccount. * <b>GLOBAL_ACCOUNT:</b> The entitlement is assigned to a root global account. * <b>DIRECTORY:</b> The entitlement is assigned to a directory.
	EntityType string `json:"entityType,omitempty"`
	// Date the subaccount has been modified. Dates and times are in UTC format.
	ModifiedDate          Time    `json:"modifiedDate,omitempty"`
	ParentAmount          float64 `json:"parentAmount,omitempty"`
	ParentId              string  `json:"parentId,omitempty"`
	ParentRemainingAmount float64 `json:"parentRemainingAmount,omitempty"`
	ParentType            string  `json:"parentType,omitempty"`
	// The requested amount when it is different from the actual amount because the request state is still in process or failed.
	RequestedAmount float64 `json:"requestedAmount,omitempty"`
	// Global account resource details
	Resources []ExternalResourceRequestPayload `json:"resources,omitempty"`
	// Information about the current state.
	StateMessage string `json:"stateMessage,omitempty"`
	// True, if an unlimited quota of this service plan assigned to the directory or subaccount in the global account. False, if the service plan is assigned to the directory or subaccount with a limited numeric quota, even if the service plan has an unlimited usage entitled on the level of the global account.
	UnlimitedAmountAssigned bool `json:"unlimitedAmountAssigned,omitempty"`
}
