/*
 * Entitlements Service
 *
 * The Entitlements service provides REST APIs that manage the assignments of entitlements and quotas to subaccounts and directories.   Entitlements and their quota are automatically assigned to the global account when a customer order is fulfilled. Use the APIs in this service to manage the distribution of this global quota to your directories and subaccounts.   NOTE: These APIs are relevant only for cloud management tools feature set B. For details and information about whether this applies to your global account, see [Cloud Management Tools - Feature Set Overview](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/caf4e4e23aef4666ad8f125af393dfb2.html).  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cis_entitlements

type DirectoryAssignmentsRequestPayload struct {
	// The quantity of the plan to assign to the specified directory. Relevant and mandatory only for plans that have a numeric quota.  Do not set if enable=TRUE is specified.
	Amount float64 `json:"amount,omitempty"`
	// Whether to automatically allocate the plans of entitlements that have a numeric quota with the amount specified in auto-distribute-amount to any new subaccount that is added to the directory in the future. For entitlements without a numeric quota, the plan is assigned to any new subaccount that is added to the directory in the future with the condition that enable=TRUE is set (autoDistributeAmount is not relevant in this case). If distribute=TRUE, the same assignment is also made to all subaccounts currently in the directory. Entitlements are subject to available quota in the directory.
	AutoAssign bool `json:"autoAssign,omitempty"`
	// The quota of the specified plan to automatically allocate to any new subaccount that is created in the future in the directory. When applying this option, you must set autoAssign=TRUE and/or distribute=TRUE. Applies only to entitlements that have a numeric quota. Entitlements are subject to available quota in the directory.
	AutoDistributeAmount int32 `json:"autoDistributeAmount,omitempty"`
	// Whether to assign the plan with the quota specified in autoDistributeAmount to subaccounts currently located in the specified directory. For entitlements without a numeric quota, such as multitenant apps, the plan is assigned to the subaccounts currently located in the directory (autoDistributeAmount is not relevant in this case). In both cases, autoAssign must be set to TRUE.
	Distribute bool `json:"distribute,omitempty"`
	// Whether to allocate the plan to the to the specified directory without quantity restrictions. Relevant and mandatory only for plans that don't have a numeric quota. Do not use if amount is specified.
	Enable bool `json:"enable,omitempty"`
	// The technical name of the entitlement to assign to the directory.
	Plan string `json:"plan"`
	// A unique identifier for service plans that can distinguish between the same service plans with different pricing plans.
	PlanUniqueIdentifier string `json:"planUniqueIdentifier,omitempty"`
	// The technical name of the entitlement (service, application, environment) to assign.
	Service string `json:"service"`
}
