/*
 * Entitlements Service
 *
 * The Entitlements service provides REST APIs that manage the assignments of entitlements and quotas to subaccounts and directories.   Entitlements and their quota are automatically assigned to the global account when a customer order is fulfilled. Use the APIs in this service to manage the distribution of this global quota to your directories and subaccounts.   NOTE: These APIs are relevant only for cloud management tools feature set B. For details and information about whether this applies to your global account, see [Cloud Management Tools - Feature Set Overview](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/caf4e4e23aef4666ad8f125af393dfb2.html).  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cis_entitlements

type ServicePlanResponseObject struct {
	// The assigned quota for maximum allowed consumption of the plan. Relevant for services that have a numeric quota assignment.
	Amount float64 `json:"amount,omitempty"`
	// Whether to automatically assign a quota of the entitlement to a subaccount when the subaccount is created in the entitlement's assigned directory.
	AutoAssign bool `json:"autoAssign,omitempty"`
	// The amount of the entitlement to automatically assign to a subaccount when the subaccount is created in the entitlement's assigned directory. Requires that autoAssign is set to TRUE, and there is remaining quota for the entitlement.
	AutoDistributeAmount int32 `json:"autoDistributeAmount,omitempty"`
	// Whether the service plan is available internally to SAP users.
	AvailableForInternal bool `json:"availableForInternal,omitempty"`
	// Whether the service plan is a beta feature.
	Beta bool `json:"beta,omitempty"`
	// The type of service offering. Possible values: * <b>PLATFORM:</b> A service required for using a specific platform; for example, Application Runtime is required for the Cloud Foundry platform. * <b>SERVICE:</b> A commercial or technical service. that has a numeric quota (amount) when entitled or assigned to a resource. When assigning entitlements of this type, use the 'amount' option instead of 'enable'. See: PUT/entitlements/v1/directories/{directoryGUID}/assignments. * <b>ELASTIC_SERVICE:</b> A commercial or technical service that has no numeric quota (amount) when entitled or assigned to a resource. Generally this type of service can be as many times as needed when enabled, but may in some cases be restricted by the service owner. When assigning entitlements of this type, use the 'enable' option instead of 'amount'. See: PUT/entitlements/v1/directories/{directoryGUID}/assignments. * <b>ELASTIC_LIMITED:</b> An elastic service that can be enabled for only one subaccount per global account. * <b>APPLICATION:</b> A multitenant application to which consumers can subscribe. As opposed to applications defined as a 'QUOTA_BASED_APPLICATION', these applications do not have a numeric quota and are simply enabled or disabled as entitlements per subaccount. * <b>QUOTA_BASED_APPLICATION:</b> A multitenant application to which consumers can subscribe. As opposed to applications defined as 'APPLICATION', these applications have an numeric quota that limits consumer usage of the subscribed application per subaccount. When maxAllowedSubaccountQuota is > 0, this is the limit that can be set when assigning the max quota entitlement of the app to any subaccount. If maxAllowedSubaccountQuota is = 0 or null, the max quota that can be entitled to any subaccount is the amount purchased by the customer (the global account quota). * <b>ENVIRONMENT:</b> An environment service; for example, Cloud Foundry.
	Category string `json:"category,omitempty"`
	// Contains information about the data centers and regions in the cloud landscape
	DataCenters []DataCenterResponseObject `json:"dataCenters,omitempty"`
	// Description of the service plan for customer-facing UIs.
	Description string `json:"description,omitempty"`
	// Display name of the service plan for customer-facing UIs.
	DisplayName string `json:"displayName,omitempty"`
	// The quota limit that is allowed for this service plan for SAP internal users. If null, the default quota limit is set to 200. Applies only when the availableForInternal property is set to TRUE.
	InternalQuotaLimit int32 `json:"internalQuotaLimit,omitempty"`
	// The maximum allowed usage quota per subaccount for multitenant applications and environments that are defined as \"quota-based\". This quota limits the usage of the application and/or environment per subaccount per a given usage metric that is defined within the application or environment by the service provider. If null, the usage limit per subaccount is the maximum free quota in the global account. For example, a value of 1 could: (1) limit the number of subscriptions to a quota-based multitenant application within a global account according to the purchased quota, or (2) restrict the enablement of a single instance of an environment per subaccount.
	MaxAllowedSubaccountQuota int32 `json:"maxAllowedSubaccountQuota,omitempty"`
	// The unique registration name of the service plan.
	Name string `json:"name,omitempty"`
	// [DEPRECATED] The source that added the service. Possible values: * <b>VENDOR:</b> The product has been added by SAP or the cloud operator to the product catalog for general use. * <b>GLOBAL_ACCOUNT_OWNER:</b> Custom services that are added by a customer and are available only for that customer’s global account. * <b>PARTNER:</b> Service that are added by partners. And only available to its customers.  Note: This property is deprecated. Please use the ownerType attribute on the entitledService level instead.
	ProvidedBy string `json:"providedBy,omitempty"`
	// The method used to provision the service plan. * <b>SERVICE_BROKER:</b> Provisioning of NEO or CF quotas done by the service broker. * <b>NONE_REQUIRED:</b> Provisioning of CF quotas done by setting amount at provisioning-service. * <b>COMMERCIAL_SOLUTION_SCRIPT:</b> Provisioning is done by a script provided by the service owner and run by the Core Commercial Foundation service. * <b>GLOBAL_COMMERCIAL_SOLUTION_SCRIPT:</b> Provisioning is done by a script provided by the service owner and run by the Core Commercial Foundation service used for Global Account level. * <b>GLOBAL_QUOTA_DOMAIN_DB:</b> Provisioning is done by setting amount at Domain DB, this is relevant for non-ui quotas only. * <b>CLOUD_AUTOMATION:</b> Provisioning is done by the cloud automation service. This is relevant only for provisioning that requires external providers that are not within the scope of CIS.
	ProvisioningMethod string `json:"provisioningMethod,omitempty"`
	// The remaining amount of the plan that can still be assigned. For plans that don't have a numeric quota, the remaining amount is always the maximum allowed quota.
	RemainingAmount float64 `json:"remainingAmount,omitempty"`
	// Remote service resources provided by non-SAP cloud vendors, and which are offered by this plan.
	Resources []ExternalResourceRequestPayload `json:"resources,omitempty"`
	// Relevant entitlements for the source that added the product.
	SourceEntitlements []EntitlementAmountResponseObject `json:"sourceEntitlements,omitempty"`
	// A unique identifier for service plans that can distinguish between the same service plans with different pricing plans.
	UniqueIdentifier string `json:"uniqueIdentifier,omitempty"`
	Unlimited        bool   `json:"unlimited,omitempty"`
}
