/*
 * Authorization
 *
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can manage service instances of the Authorization and Trust Management service. You can also manage roles, role templates, and role collections of your subaccount.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package xsuaa_authz

type Subscriptions struct {
	// Only relevant for reuse instances. Total number of following instances of your broker service instance. The service only returns this array if the service instance uses the broker plan.
	CloneCount int32 `json:"cloneCount,omitempty"`
	// An array of subscriptions to your multitenant application for this tenant. The service only returns this array if you set the listSubscriptions query paramter to true.
	Subscriptions []SubscriptionDetails `json:"subscriptions,omitempty"`
	// The number of subscriptions to your multitenant application for this tenant.
	SubscriptionCountForTenant int32 `json:"subscriptionCountForTenant,omitempty"`
	// Only relevant for reuse instances. An array of following instances of your broker service instance. The service only returns this array if you set the listCloneSubscriptions query paramter to true and the service instance uses the broker plan.
	CloneSubscriptions []CloneSubscriptionDetails `json:"cloneSubscriptions,omitempty"`
	// Total number of refrences to the broker service instance.
	ReferenceCount int32 `json:"referenceCount,omitempty"`
	// Only relevant for reuse instances. Total number of subscriptions to following service instances.
	CloneSubscriptionCount int32 `json:"cloneSubscriptionCount,omitempty"`
	// Total number of subscriptions to your multitenant application.
	SubscriptionCount int32 `json:"subscriptionCount,omitempty"`
}
