/*
 * Authorization
 *
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can manage service instances of the Authorization and Trust Management service. You can also manage roles, role templates, and role collections of your subaccount.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package xsuaa_authz

type SamlAttrAssignment struct {
	RoleCollectionIdentityZone string `json:"roleCollectionIdentityZone,omitempty"`
	RoleCollectionName         string `json:"roleCollectionName,omitempty"`
	// This parameter is deprecated.
	SamlAttrName string `json:"samlAttrName,omitempty"`
	// The name of the attribute parameter.
	AttributeName string `json:"attributeName,omitempty"`
	// This parameter is deprecated.
	SamlAttributeValue string `json:"samlAttributeValue,omitempty"`
	// The value of the attribute.
	AttributeValue string `json:"attributeValue,omitempty"`
	// The operator value that matches the attribute name to its value.
	ComparisonOperator string `json:"comparisonOperator,omitempty"`
	SamlEntityId       string `json:"samlEntityId,omitempty"`
	IdentityProvider   string `json:"idpDisplayName,omitempty"`
}
