/*
 * Authorization
 *
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can manage service instances of the Authorization and Trust Management service. You can also manage roles, role templates, and role collections of your subaccount.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package xsuaa_authz

type OAuth2Configuration struct {
	Allowedproviders     []string `json:"allowedproviders,omitempty"`
	Autoapprove          bool     `json:"autoapprove,omitempty"`
	GrantTypes           []string `json:"grant-types,omitempty"`
	RedirectUris         []string `json:"redirect-uris,omitempty"`
	RefreshTokenValidity int32    `json:"refresh-token-validity,omitempty"`
	SystemAttributes     []string `json:"system-attributes,omitempty"`
	TokenValidity        int32    `json:"token-validity,omitempty"`
}
