/*
 * Authorization
 *
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can manage service instances of the Authorization and Trust Management service. You can also manage roles, role templates, and role collections of your subaccount.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package xsuaa_authz

type Idp struct {
	TenantType   string  `json:"tenantType"`
	DisplayName  *string `json:"displayName"`
	CommonHost   string  `json:"commonHost"`
	Description  string  `json:"description"`
	CustomHost   *string `json:"customHost"`
	CustomerName *string `json:"customerName"`
	CostCenterId int64   `json:"costCenterId"`
	DataCenterId string  `json:"dataCenterId"`
	Host         string  `json:"host"`
	CustomerId   *string `json:"customerId"`
	TenantId     string  `json:"tenantId"`
	Region       string  `json:"region"`
	Status       string  `json:"status"`
}
