/*
 * Authorization
 *
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can manage service instances of the Authorization and Trust Management service. You can also manage roles, role templates, and role collections of your subaccount.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package xsuaa_authz

type IdentityProviderMapping struct {
	// The name of the attribute that you want to add.
	AttributeName string `json:"attributeName,omitempty"`
	// The value of the attribute that you want to add.
	AttributeValue string `json:"attributeValue,omitempty"`
	// The operator value that matches the attribute name to its value.
	Operator string `json:"operator,omitempty"`
	// The name of the role collection.
	RoleCollectionName string `json:"roleCollectionName,omitempty"`
}
