/*
 * Authorization
 *
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can manage service instances of the Authorization and Trust Management service. You can also manage roles, role templates, and role collections of your subaccount.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package xsuaa_authz

type RoleTemplate struct {
	AppDescription string `json:"appDescription,omitempty"`
	// The application ID is the xsappname plus the identifier, which consists of an exclamation mark (!), an identifier for the plan underwhich the application is deployed, and an index number.
	AppId               string               `json:"appId,omitempty"`
	AppName             string               `json:"appName,omitempty"`
	AttributeReferences []AttributeReference `json:"attribute-references,omitempty"`
	DefaultRoleName     string               `json:"default-role-name,omitempty"`
	Description         string               `json:"description,omitempty"`
	// The name has a maximum length of 64 characters. Only the following characters are allowed: alphanumeric characters (aA-zZ) and (0-9) and underscore (_).
	Name            string   `json:"name,omitempty"`
	RoleReferences  []Role   `json:"role-references,omitempty"`
	ScopeReferences []string `json:"scope-references,omitempty"`
	Version         string   `json:"version,omitempty"`
}
