/*
 * Authorization
 *
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can manage service instances of the Authorization and Trust Management service. You can also manage roles, role templates, and role collections of your subaccount.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package xsuaa_authz

type App struct {
	// The application ID is the xsappname plus the identifier, which consists of an exclamation mark (!), an identifier for the plan underwhich the application is deployed, and an index number.
	Appid                  string               `json:"appid,omitempty"`
	Attributes             []AppAttribute       `json:"attributes,omitempty"`
	Authorities            []string             `json:"authorities,omitempty"`
	Description            string               `json:"description,omitempty"`
	ForeignScopeReferences []string             `json:"foreign-scope-references,omitempty"`
	MasterAppId            *string              `json:"masterAppId,omitempty"`
	Oauth2Configuration    *OAuth2Configuration `json:"oauth2-configuration,omitempty"`
	OrgId                  string               `json:"orgId,omitempty"`
	PlanId                 string               `json:"planId,omitempty"`
	PlanName               string               `json:"planName,omitempty"`
	RoleTemplates          []RoleTemplate       `json:"role-templates,omitempty"`
	Scopes                 []Scope              `json:"scopes,omitempty"`
	Serviceinstanceid      string               `json:"serviceinstanceid,omitempty"`
	SpaceId                *string              `json:"spaceId,omitempty"`
	TenantMode             string               `json:"tenant-mode,omitempty"`
	UserName               *string              `json:"userName,omitempty"`
	// The name of the application as defined in the application security descriptor xs-security.json. The name has a maximum length of 128 characters. Only the following characters are allowed: alphanumeric characters (aA-zZ) and (0-9), hyphen (-), underscore (_), forward slash (/), and backslash (\\).
	Xsappname string `json:"xsappname,omitempty"`
}
