/*
 * Authorization
 *
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can manage service instances of the Authorization and Trust Management service. You can also manage roles, role templates, and role collections of your subaccount.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package xsuaa_authz

// The array groupReferences is deprecated and only provided to maintain backward compatibility. Please use the array samlAttrAssignment instead.
type GroupReference struct {
	DEPRECTAED string `json:"DEPRECTAED,omitempty"`
}
