name: 🐞 Bug report
description: File a bug/issue to help us improve
title: "[BUG]"
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: area
    attributes:
      label: What type of issue are you facing
      description: What type of issue are you facing?
      options:
        - bug report
        - documentation issue
        - regression (a behavior that used to work and stopped in a new version)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        Describe the steps to reproduce the observed behavior.

        Tip: You can attach your HCL files and Terraform scripts here by clicking this area to highlight it and then dragging files in.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Add screenshots to help explain your problem
      description: |
        If applicable, add screenshots to help explain your problem.

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context like links or references about the problem here. Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
