name: 💡Feature request
description: Suggest an idea for this project
title: "[FEATURE]"
labels: [enhancement, needs-triage]
body:
  - type: dropdown
    attributes:
      label: What area do you want to see improved?
      description: Specify the main area that you want to see improved.
      options:
        - terraform provider
        - documentation
        - examples
        - other
    validations:
      required: true
  - type: textarea
    id: area
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: Provide a clear and concise description of what the problem is e.g., I am always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context like links or references about the problem here. Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
