/*
 * Provisioning Service
 *
 * The Provisioning service provides REST APIs that are responsible for the provisioning and deprovisioning of environment instances and tenants in the corresponding region.  Provisioning is performed after validation by the Entitlements service. Use the APIs in this service to manage and create environment instances, such as a Cloud Foundry org, in a subaccount and to retrieve the plans and quota assignments for a subaccount.  NOTE: These APIs are relevant only for cloud management tools feature set B. For details and information about whether this applies to your global account, see [Cloud Management Tools - Feature Set Overview](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/caf4e4e23aef4666ad8f125af393dfb2.html).  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package provisioning

type EnvironmentInstanceResponseObject struct {
	// The ID of the associated environment broker.
	BrokerId string `json:"brokerId,omitempty"`
	// The commercial type of the environment broker.
	CommercialType string `json:"commercialType,omitempty"`
	// The date the environment instance was created. Dates and times are in UTC format.
	CreatedDate Time `json:"createdDate"`
	// Custom labels that are defined by a user and assigned as key-value pairs in a JSON array to the environment instance.  Example: {   \"Cost Center\": [\"19700626\"],   \"Department\": [\"Sales\"],   \"Contacts\": [\"name1@example.com\",\"name2@example.com\"],   \"EMEA\":[] } NOTE: Custom labels apply only to SAP BTP. They are not the same labels that might be defined by your environment broker (see \"labels\" field).
	CustomLabels map[string][]string `json:"customLabels,omitempty"`
	// The URL of the service dashboard, which is a web-based management user interface for the service instances.
	DashboardUrl string `json:"dashboardUrl,omitempty"`
	// The description of the environment instance.
	Description string `json:"description,omitempty"`
	// Type of the environment instance that is used.
	EnvironmentType string `json:"environmentType,omitempty"`
	// The GUID of the global account that is associated with the environment instance.
	GlobalAccountGUID string `json:"globalAccountGUID,omitempty"`
	// Automatically generated unique identifier for the environment instance.
	Id string `json:"id,omitempty"`
	// Broker-specified key-value pairs that specify attributes of an environment instance.
	Labels string `json:"labels,omitempty"`
	// The name of the landscape within the logged-in region on which the environment instance is created.
	LandscapeLabel string `json:"landscapeLabel,omitempty"`
	// The last date the environment instance was last modified. Dates and times are in UTC format.
	ModifiedDate Time `json:"modifiedDate"`
	// Name of the environment instance.
	Name string `json:"name,omitempty"`
	// An identifier that represents the last operation. This ID is returned by the environment brokers.
	Operation string `json:"operation,omitempty"`
	// Configuration parameters for the environment instance.
	Parameters string `json:"parameters,omitempty"`
	// ID of the service plan for the environment instance in the corresponding service broker's catalog.
	PlanId string `json:"planId,omitempty"`
	// Name of the service plan for the environment instance in the corresponding service broker's catalog.
	PlanName string `json:"planName,omitempty"`
	// ID of the platform for the environment instance in the corresponding service broker's catalog.
	PlatformId string `json:"platformId,omitempty"`
	// ID of the service for the environment instance in the corresponding service broker's catalog.
	ServiceId string `json:"serviceId,omitempty"`
	// Name of the service for the environment instance in the corresponding service broker's catalog.
	ServiceName string `json:"serviceName,omitempty"`
	// Current state of the environment instance.
	State string `json:"state,omitempty"`
	// Information about the current state of the environment instance.
	StateMessage string `json:"stateMessage,omitempty"`
	// The GUID of the subaccount associated with the environment instance.
	SubaccountGUID string `json:"subaccountGUID,omitempty"`
	// The ID of the tenant that owns the environment instance.
	TenantId string `json:"tenantId,omitempty"`
	// The last provisioning operation on the environment instance. * <b>Provision:</b> Environment instance created. * <b>Update:</b> Environment instance changed. * <b>Deprovision:</b> Environment instance deleted.
	Type_ string `json:"type,omitempty"`
}
