/*
 * SaaS Provisioning Service
 *
 * The SAP SaaS Provisioning service provides REST APIs that are responsible for the registration and provisioning of multitenant applications and services.   Use the APIs in this service to perform various operations related to your multitenant applications and services. For example, to get application registration details, subscribe a tenant to your application, unsubscribe a tenant from your application, retrieve all your application subscriptions, update subscription dependencies, and to get subscription job information.  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saas_manager_service

type RegistrationDetailsResponseObject struct {
	// The ID returned by an xsuaa service instance after the app provider has connected the multitenant application to an xsuaa service instance.
	AppId string `json:"appId,omitempty"`
	// The unique registration name of the deployed multitenant application as defined by the app developer.
	AppName string `json:"appName,omitempty"`
	// The plan used to register the multitenant application or reusable service. <b>- saasApplication:</b> Registered entity is a multitenant application. <b>- saasService:</b> Registered entity is a reuse service.
	AppType string `json:"appType,omitempty"`
	// Any callback URLs that the multitenant application exposes.
	AppUrls string `json:"appUrls,omitempty"`
	// Name of the cloud automation solution associated with the multitenant application.
	AutomationSolutionName string `json:"automationSolutionName,omitempty"`
	// The category to which the application is grouped in the Subscriptions page in the cockpit. If left empty, it gets assigned to the default category.
	Category string `json:"category,omitempty"`
	// The unique commercial registration name of the deployed multitenant application as defined by the app developer.
	CommercialAppName string `json:"commercialAppName,omitempty"`
	// The description of the multitenant application for customer-facing UIs.
	Description string `json:"description,omitempty"`
	// The display name of the application for customer-facing UIs.
	DisplayName string `json:"displayName,omitempty"`
	// A flag to determine wheater to fail subscription when automation solution fails or not.
	FailSubscriptionOnAutomationFailure bool `json:"failSubscriptionOnAutomationFailure,omitempty"`
	// Name of the formations solution associated with the multitenant application.
	FormationSolutionName string `json:"formationSolutionName,omitempty"`
	// ID of the global account associated with the multitenant application.
	GlobalAccountId string `json:"globalAccountId,omitempty"`
	// Error message to return when automation solution fails.
	MessageOnAutomationFailure string `json:"messageOnAutomationFailure,omitempty"`
	// The unique ID of the Cloud Foundry org where the app provider has deployed and registered the multitenant application.
	OrganizationGuid string `json:"organizationGuid,omitempty"`
	// JSON schema that describes the parameters that the consumer must provide when subscribing to the application.
	ParamsSchema map[string]interface{} `json:"paramsSchema,omitempty"`
	// Whether the parameters are transferred to the application’s dependencies.
	PropagateParams bool `json:"propagateParams,omitempty"`
	// The unique ID of the tenant that provides the multitenant application.
	ProviderTenantId string `json:"providerTenantId,omitempty"`
	// The ID of the multitenant application that is registered to the SAP SaaS Provisioning service registry.
	ServiceInstanceId string `json:"serviceInstanceId,omitempty"`
	// The unique ID of the Cloud Foundry space where the app provider has deployed and registered the multitenant application.
	SpaceGuid string `json:"spaceGuid,omitempty"`
	// The xsappname configured in the security descriptor file used to create the xsuaa service instance for the multitenant application.
	Xsappname string `json:"xsappname,omitempty"`
}
