/*
 * SaaS Provisioning Service
 *
 * The SAP SaaS Provisioning service provides REST APIs that are responsible for the registration and provisioning of multitenant applications and services.   Use the APIs in this service to perform various operations related to your multitenant applications and services. For example, to get application registration details, subscribe a tenant to your application, unsubscribe a tenant from your application, retrieve all your application subscriptions, update subscription dependencies, and to get subscription job information.  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saas_manager_service

type JobStateResponseObject struct {
	// The service instance ID of the SAP SaaS Provisioning service (saas-registry) that the application is using.
	CreatedBy string                  `json:"createdBy,omitempty"`
	Error_    *JobErrorResponseObject `json:"error,omitempty"`
	// ID of the corresponding job.
	Id string `json:"id,omitempty"`
	// The current state of the corresponding job. Possible values: * <b>CREATED:</b> Job processing has created. * <b>STARTED:</b> Job processing has started. * <b>SUCCEEDED:</b> The job has completed. * <b>FAILED:</b> The job failed and did not complete. * <b>RETRY:</b> Subscription has timed out and job processing is pending a retry.
	State string `json:"state,omitempty"`
}
