/*
 * SaaS Provisioning Service
 *
 * The SAP SaaS Provisioning service provides REST APIs that are responsible for the registration and provisioning of multitenant applications and services.   Use the APIs in this service to perform various operations related to your multitenant applications and services. For example, to get application registration details, subscribe a tenant to your application, unsubscribe a tenant from your application, retrieve all your application subscriptions, update subscription dependencies, and to get subscription job information.  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saas_manager_service

type JobErrorResponseObject struct {
	// Description of the error.
	Error_ string `json:"error,omitempty"`
	// The runtime exception for the error.
	Exception string `json:"exception,omitempty"`
	// The message associated with the current error.
	Message string `json:"message,omitempty"`
	// Path of the exception received from the server.
	Paths string `json:"paths,omitempty"`
	// Error status code.
	Status    int32      `json:"status,omitempty"`
	Timestamp *Timestamp `json:"timestamp,omitempty"`
}
