/*
 * SaaS Provisioning Service
 *
 * The SAP SaaS Provisioning service provides REST APIs that are responsible for the registration and provisioning of multitenant applications and services.   Use the APIs in this service to perform various operations related to your multitenant applications and services. For example, to get application registration details, subscribe a tenant to your application, unsubscribe a tenant from your application, retrieve all your application subscriptions, update subscription dependencies, and to get subscription job information.  See also: * [Authorization](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/3670474a58c24ac2b082e76cbbd9dc19.html) * [Rate Limiting](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77b217b3f57a45b987eb7fbc3305ce1e.html) * [Error Response Format](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/77fef2fb104b4b1795e2e6cee790e8b8.html) * [Asynchronous Jobs](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/latest/en-US/0a0a6ab0ad114d72a6611c1c6b21683e.html)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package saas_manager_service

type EntitledApplicationsResponseObject struct {
	// The list of features specific to this plan.
	AdditionalPlanFeatures []string `json:"additionalPlanFeatures,omitempty"`
	// The ID returned by XSUAA after the app provider has performed a bind of the multitenant application to a XSUAA service instance.
	AppId string `json:"appId,omitempty"`
	// The unique registration name of the deployed multitenant application as defined by the app developer.
	AppName string `json:"appName,omitempty"`
	// The application coordinates provided in metadata for customer-facing UIs.
	ApplicationCoordinates *interface{} `json:"applicationCoordinates,omitempty"`
	// The authentication provider of the multitenant application. * XSUAA is the SAP Authorization and Trust Management service that defines scopes and permissions for users as tenants at the global account level. * IAS is Identity Authentication Service that defines scopes and permissions for users in zones (common data isolation systems across systems, SaaS tenants, and services).
	AuthenticationProvider string `json:"authenticationProvider,omitempty"`
	// The state of the automation solution.
	AutomationState string `json:"automationState,omitempty"`
	// The message that describes the automation solution state.
	AutomationStateMessage string `json:"automationStateMessage,omitempty"`
	// The technical name of the category defined by the app developer to which the multitenant application is grouped in customer-facing UIs.
	Category string `json:"category,omitempty"`
	// The display name of the category for customer-facing UIs.
	CategoryDisplayName string `json:"categoryDisplayName,omitempty"`
	// The commercial name of the deployed multitenant application as defined by the app developer.
	CommercialAppName string `json:"commercialAppName,omitempty"`
	// The date the subscription was created. Dates and times are in UTC format.
	CreatedDate Time `json:"createdDate,omitempty"`
	// Whether the application was developed by a customer. If not, then the application is developed by the cloud operator, such as SAP.
	CustomerDeveloped bool `json:"customerDeveloped,omitempty"`
	// The description of the multitenant application for customer-facing UIs.
	Description string `json:"description,omitempty"`
	// The display name of the application for customer-facing UIs.
	DisplayName string `json:"displayName,omitempty"`
	// Name of the formations solution associated with the multitenant application.
	FormationSolutionName string `json:"formationSolutionName,omitempty"`
	// ID of the associated global account.
	GlobalAccountId string `json:"globalAccountId,omitempty"`
	// The icon of the multitenant application for customer-facing UIs.
	IconBase64 string `json:"iconBase64,omitempty"`
	// The application's incident-tracking component provided in metadata for customer-facing UIs.
	IncidentTrackingComponent string `json:"incidentTrackingComponent,omitempty"`
	// User-defined labels that are assigned as key-value pairs in a JSON array to the multitenant application subscription.  Example: {   \"Cost Center\": [\"19700626\"],   \"Department\": [\"Sales\"],   \"Contacts\": [\"name1@example.com\",\"name2@example.com\"],   \"EMEA\":[] }
	Labels map[string][]string `json:"labels,omitempty"`
	// JSON schema that describes the metadata that the consumer provide when subscribing to the application.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// The date the subscription was last modified. Dates and times are in UTC format.
	ModifiedDate Time `json:"modifiedDate,omitempty"`
	// JSON schema that describes the parameters that the consumer must provide when subscribing to the application.
	ParamsSchema map[string]interface{} `json:"paramsSchema,omitempty"`
	// The description of the plan for customer-facing UIs.
	PlanDescription string `json:"planDescription,omitempty"`
	// The plan name of the application to which the consumer has subscribed.
	PlanName string `json:"planName,omitempty"`
	// ID of the landscape-specific environment.
	PlatformEntityId string `json:"platformEntityId,omitempty"`
	// Total amount the subscribed subaccount is entitled to consume.
	Quota int32 `json:"quota,omitempty"`
	// The short description of the multitenant application for customer-facing UIs.
	ShortDescription string `json:"shortDescription,omitempty"`
	// The subscription state of the subaccount regarding the multitenant application.
	State string `json:"state,omitempty"`
	// The ID of the subaccount which is subscribed to the multitenant application.
	SubscribedSubaccountId string `json:"subscribedSubaccountId,omitempty"`
	// The ID of the tenant which is subscribed to a multitenant application.
	SubscribedTenantId string                                   `json:"subscribedTenantId,omitempty"`
	SubscriptionError  *EntitledApplicationsErrorResponseObject `json:"subscriptionError,omitempty"`
	// Technical ID generated by XSUAA for a multitenant application when a consumer subscribes to the application.
	SubscriptionGUID string `json:"subscriptionGUID,omitempty"`
	// URL for app users to launch the subscribed application.
	SubscriptionUrl string `json:"subscriptionUrl,omitempty"`
	// Specifies whether a consumer, whose subaccount is subscribed to the application, can change its subscriptions parameters.
	SupportsParametersUpdates bool `json:"supportsParametersUpdates,omitempty"`
	// Specifies if a consumer, whose subaccount is subscribed to the application, can change the subscription to a different plan that is available for this application and subaccount.
	SupportsPlanUpdates bool `json:"supportsPlanUpdates,omitempty"`
	// Tenant ID of the application provider.
	TenantId string `json:"tenantId,omitempty"`
}
