/*
 * User Management (System for Cross-domain Identity Management (SCIM))
 *
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can provision users from identity providers and manage roles and role collections. Use this API to manage shadow users; users the service provisions from your identity provider to the subaccount. For more information, see [Switch Off Automatic Creation of Shadow Users](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d8525671e8b14147b96ef497e1e1af80.html). The System for Cross-domain Identity Management (SCIM) interfaces for users and groups supplement the relevant UAA [users](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#users)and [groups](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#groups) interfaces. Groups in the Authorization and Trust Management service are mapped to role collections. See also [SAP Note 2760424]( https://launchpad.support.sap.com/#/notes/2760424). To enable access to this API, create an OAuth 2.0 client for the XSUAA service instance. To create the client, enable the apiaccess plan. For more information, see [Access UAA Admin APIs](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/ebc9113a520e495ea5fb759b9a7929f2.html).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package xsuaa_plattform

import (
	"time"
)

type ScimUserPostPut struct {
	// The user ID of a SCIM user.
	Id         string    `json:"id,omitempty"`
	ExternalId string    `json:"externalId,omitempty"`
	Meta       *ScimMeta `json:"meta,omitempty"`
	UserName   string    `json:"userName,omitempty"`
	Name       *Name     `json:"name,omitempty"`
	Emails     []Email   `json:"emails,omitempty"`
	// A list of approval decisions made by this user. Approvals record the user's explicit approval or rejection for an application's request for delegated permissions.
	Approvals []Approval `json:"approvals,omitempty"`
	Active    bool       `json:"active,omitempty"`
	Verified  bool       `json:"verified,omitempty"`
	// The identity provider hosting the users. For the default identity provider, use sap.default. Subaccounts created before October 2020 return ldap as the default identity provider. The system accepts both sap.default and ldap for the default identity provider, but returns sap.default or ldap depending on when the subaccount was created.
	Origin               string        `json:"origin,omitempty"`
	ZoneId               string        `json:"zoneId,omitempty"`
	DisplayName          string        `json:"displayName,omitempty"`
	Locale               string        `json:"locale,omitempty"`
	NickName             string        `json:"nickName,omitempty"`
	PasswordLastModified time.Time     `json:"passwordLastModified"`
	PreviousLogonTime    int64         `json:"previousLogonTime,omitempty"`
	LastLogonTime        int64         `json:"lastLogonTime,omitempty"`
	Schemas              []string      `json:"schemas,omitempty"`
	PhoneNumbers         []PhoneNumber `json:"phoneNumbers,omitempty"`
	PreferredLanguage    string        `json:"preferredLanguage,omitempty"`
	ProfileUrl           string        `json:"profileUrl,omitempty"`
	Salt                 string        `json:"salt,omitempty"`
	Timezone             string        `json:"timezone,omitempty"`
	Title                string        `json:"title,omitempty"`
	UserType             string        `json:"userType,omitempty"`
}
