/*
 * CDR API Specification
 *
 * The specification for public APIs of Central Disaster Recovery services.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cdr

type CreateSubaccountPairResponse struct {
	// create success message
	Message string `json:"message"`
}
