/*
 * CDR API Specification
 *
 * The specification for public APIs of Central Disaster Recovery services.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cdr

type SubaccountDrMetadata struct {
	// The ID of the subaccount.
	Id string `json:"id,omitempty"`
	// The region of the subaccount.
	Region string `json:"region,omitempty"`
	// The subdomain of the subaccount.
	Subdomain string `json:"subdomain,omitempty"`
}
