/*
 * CDR API Specification
 *
 * The specification for public APIs of Central Disaster Recovery services.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cdr

type CreateSubaccountPairRequest struct {
	// The ID of the subaccount to pair with.
	SubaccountId string `json:"subaccount_id"`
}
