/*
 * CDR API Specification
 *
 * The specification for public APIs of Central Disaster Recovery services.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cdr

type GetSubaccountPairResponse struct {
	// The ID of the subaccount pair.
	Id string `json:"id"`
	// The timestamp when the subaccount pair was created.
	CreatedAt int64 `json:"created_at"`
	// The user who created the subaccount pair.
	CreatedBy string `json:"created_by,omitempty"`
	// The ID of the global account.
	GlobalAccountId string                 `json:"global_account_id"`
	Subaccounts     []SubaccountDrMetadata `json:"subaccounts"`
}
