/*
 * CDR API Specification
 *
 * The specification for public APIs of Central Disaster Recovery services.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cdr

type ErrorMessage struct {
	// Description about the error
	ErrorMessage string `json:"error_message,omitempty"`
	// String representing the error code, which is used to identify the type of error
	ErrorCode string `json:"error_code,omitempty"`
	// The ID of the request, which is generated by the server or the client
	RequestId string `json:"request_id,omitempty"`
}
