name: Compatibility Test - OpenTofu

on:
  workflow_dispatch:

env:
  PATH_TO_TFSCRIPT: 'regression-test'
  DEV_OVERRIDE: 'assets/provider-config-ghaction.txt'


jobs:
  execute_regression_test:
    name: Regression Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      id: checkout_repo
      uses: actions/checkout@v4
      
    - name: Setup OpenTofu
      id : setup_opentofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_wrapper: false
        tofu_version: latest

    - name: Tofu Init
      id: tofu_init
      shell: bash
      run: |
        tofu -chdir=${{ env.PATH_TO_TFSCRIPT }} init -no-color

    - name: Tofu Apply
      id: tofu_apply
      shell: bash
      run: |
        export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
        export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
        tofu -chdir=${{ env.PATH_TO_TFSCRIPT }} apply -var globalaccount='${{ secrets.GLOBALACCOUNT }}' -var idp='${{ secrets.BTP_IDP }}' -auto-approve -no-color 

    - name: Tofu Destroy
      if: always()  
      id: tofu_destroy
      shell: bash
      run: |
        export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
        export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
        tofu -chdir=${{ env.PATH_TO_TFSCRIPT }} destroy -var globalaccount='${{ secrets.GLOBALACCOUNT }}' -var idp='${{ secrets.BTP_IDP }}' -auto-approve -no-color

    - name: Error in execution - create or update issue
      uses: JasonEtco/create-an-issue@v2
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: assets/compat_template.md
        update_existing: true
