name: REUSE Compliance Check
# To manually verify/falsify reuse check results

on:
  workflow_dispatch:

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5